### PR TITLE
Multi-line Charts implemented

### PR DESCRIPTION
**Pull request by a-tamang**
**Main changes:** 
- _data_ now takes an array of an array of coordinates (to facilitate multiple line graphs).
- _color_, _fillColor_, etc that took a single string now take an array as well, for the same reason above.
- empty values, that will signify a rendering of the position for the data plot but not the data plot itself, is            now signified by an empty string: ''

**Possible Code Improvements:** 
- Ctrl-F all the 'data[0]' that were added. This could be replaced by a more general implementation however, throughout my testing and use with my own projects, no error has stemmed from this.

**General Comments:**
- I forked your project since I required the multi-line graphs functionality immediately for a project I was working on; as such, this implementation does indeed work. Please let me know if you don't understand my logic for a certain part of the code.

### CODE REVIEW

**Comment by madpau1** [comment]
@a-tamang solve conflicts please

**Comment by tomauty** [comment]
Merged. Thank you. I'll be resuming work on this project next week. Sorry for my absence. I'll make sure this works with RN SVG.

**Comment by zhaixiaoou** [comment]
@tomauty  I  npm install react-native-chart --save,but  didn't seem to update any code。i can not use multi line chart

**Comment by uriklar** [comment]
Has this PR been reverted? I see it was merged, but it doesn't appear in master..

**Pull request merged**
