### PR TITLE
Adds ability to set horizontalGridStep

### PR DESCRIPTION
**Pull request by jakkra**
When displaying more than 100 or something data points, the graph gets extremely messy. I added functionality to not render one grid line for every X-value data point. 

There is one issue thought, sometimes even if I set `horizontalGridStep={someValue}` it sometimes shows SomeValue + 1 when this happens the x label is not exactly aligned with the axis. I didn't have time to dig into the code to much, but thought you could do something with my code anyway, the bug might be an easy fix. My current solution is better than the current, which is not very useful with big data sets.

How it looks before:
Before

How it looks after:
- first graph `horizontalGridStep={5}`
- second `horizontalGridStep={4}` 

after

### CODE REVIEW

**Comment by tomauty** [comment]
This is great. Thank you.

**Comment by rpastorelle** [comment]
This is a really, really good & much needed update. Nice job, @jakkra!

One thing I noticed, while using this is that the scale seems a bit off:

The first chart is without using this prop. Notice how the 2nd & 3rd differ with respect to the y-axis labels. The 5th data point should be at 5:28p; However, in the last example, it looks to be after 7:06p. 

I also think it should always label the last data point. That's getting kind of needy tho :)

horizontalgridstep

**Comment by jakkra** [comment]
@rpastorelle Ah, didn't notice that with my data set. I'm looking into it. If the data set is not dividable by the horizontalGridStep, it will result in wrongly placed grids. So some other solution is needed to fix that. Will see what I can do.

**Comment by jakkra** [comment]
Changing calculation of `stepsBetweenVerticalLines`  to:
`let stepsBetweenVerticalLines = this.props.horizontalGridStep ? Math.floor((data.length) / this.props.horizontalGridStep) : 1;` will fix that wrong labels are shown and fix that lines doesn't align with data points. However I found that when data.length and horizontalGridStep have the same parity, the lines won't align with the data point. 

Came up with a solution, but it will still break when data.length is a prime number :/

**Pull request merged**
