### PR TITLE
Optionally hide horizontal or vertical grid lines

### PR DESCRIPTION
**Pull request by mahlon-gumbs**
Currently the grid lines are all or none via showGrid. We needed a way to optionally hide the vertical or horizontal grid lines.
- hideHorizontalGridLines will hide the horizontal grid lines if showGrid is true
- hideVerticalGridLines will hide the vertical grid lines if showGrid is true

### CODE REVIEW

**Comment by tomauty** [comment]
Could you add it to the README as well? Then I'll merge. Thanks!

**Comment by tomauty** [comment]
Also, we can use `PropTypes` instead of `_reactNative.PropTypes` :)

**Comment by mahlon-gumbs** [comment]
Sorry about that. Should be fixed up with PropTypes now. Readme updated as well.

**Comment by tomauty** [comment]
No worries! Will have a second look tonight and merge if no issues : )

**Comment by mahlon-gumbs** [comment]
Awesome. Thanks.

**Pull request merged**
